services:
  db:
    image: mysql:8.0
    container_name: hearttrack_db
    command: --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hearttrack
      MYSQL_USER: hearttrack_user
      MYSQL_PASSWORD: hearttrack_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hearttrack_network

  classifier:
    build:
      context: ./hearttrack-classifier
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - hearttrack_network

  backend:
    build:
      context: ./hearttrack-backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - classifier
      - db
    networks:
      - hearttrack_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=hearttrack
      - DB_USER=hearttrack_user
      - DB_PASSWORD=hearttrack_password
      - CL_HOST=classifier
      - CL_PORT=5000

volumes:
  db_data:

networks:
  hearttrack_network:
